import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/styles.module.css'
import Header from '../components/Header'
import Navigation from '../components/Navigation'
import Project from '../components/Project'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })


/* 
To Do: 
Update contact section to take inputs
*/

export default function Home() {
  return (
    <>
      <Head>
        <title>Maximilian Holzmann</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['body']}>

      {/* navigation also displays my header, which I dislike but will find a better solution as I flesh out the project */}
      <Navigation></Navigation>
      
      <Footer></Footer>
      </main>
      </>
  )
}
